name: Run UI Tests with Playwright

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run tests with NUnit and Playwright
      run: dotnet test --settings ./Runsettings/Test.runsettings --logger:trx --results-directory ./TestResults

    - name: Install Allure Commandline
      run: |
        curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
        unzip allure.zip -d ./allure
        sudo mv ./allure/allure-2.14.0 /usr/local/bin/allure

    - name: Generate Allure Report
      run: |
        allure generate ./TestResults --clean -o allure-report

    - name: Upload Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report

    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./TestResults