name: Playwright UI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  REPO_NAME: GITHUB_REPOSITORY
  
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Install Playwright
      run: npx playwright install

    - name: Run tests
      run: dotnet test --settings TestSettings.runsettings

    - name: Load test report history
      if: always()
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Build test report
      if: always()
      uses: simple-elf/allure-report-action@v1.11
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: ./Tests/bin/Debug/net8.0/allure-results

    - name: Publish test report
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
        publish_branch: gh-pages
        
    - name: repo name
      run: echo env.REPO_NAME
